project:
    image: images
    jwtSecret: N9tX3I1JrXhN4xvGQ5XkM2lY8sQmRkP2cH9vL8tD6Ww=
    jwtExpirationMs: 300000
    jwtCookieName: springBootEcom

spring:
  application:
    name: shop-api
  
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

    hibernate:
      ddl-auto: update
